markrogoyski/math-php

- src/Functions/Special.php
This function is used in the ChiSquared CDF among others I'm sure.
Regularized Incomplete beta is used in Student-T CDF and F Distribution CDF
> Added Lower Incomplete Gamma and Regularized Incomplete Beta

- src/Functions/Special.php
Two bugs...The incomplete beta reduces to beta when x=1, while the regularized incomplete reduces to 1 when x=1.
The case where b is an int and a is not was not included in this function.
> Fixed incorrect result when b is an integer and a is not

- src/Functions/Special.php
Incomplete_beta = regularized_incomplete_beta * beta
> Added incomplete beta

- src/Functions/Special.php
...To compliment the existing Lower Incomplete Gamma
> Added Upper Incomplete Gamma

- .travis.yml
- src/Statistics/RandomVariable.php
Added Travis CI integration and fixed the errors that it threw.
> Add travis CI integration

- src/Probability/Distribution/Continuous/Beta.php
- src/Probability/Distribution/Continuous/Cauchy.php
- src/Probability/Distribution/Continuous/ChiSquared.php
- src/Probability/Distribution/Continuous/Exponential.php
- src/Probability/Distribution/Continuous/F.php
- src/Probability/Distribution/Continuous/Laplace.php
- src/Probability/Distribution/Continuous/LogLogistic.php
- src/Probability/Distribution/Continuous/LogNormal.php
- src/Probability/Distribution/Continuous/Logistic.php
- src/Probability/Distribution/Continuous/Normal.php
- src/Probability/Distribution/Continuous/Pareto.php
- src/Probability/Distribution/Continuous/StandardNormal.php
- src/Probability/Distribution/Continuous/StudentT.php
- src/Probability/Distribution/Continuous/Uniform.php
- src/Probability/Distribution/Continuous/Weibull.php
Added a getMeans() function to each distribution.
> Distribution means

- src/LinearAlgebra/FunctionMatrix.php
- src/LinearAlgebra/Matrix.php
- tests/LinearAlgebra/FunctionMatrixTest.php
Extended the Matrix class to allow an array of functions, which can be evaluated with an array of parameters.
> Function matrix

- src/Statistics/Average.php
- tests/Statistics/AverageTest.php
Added a function to return the kth smallest element in an array,
> Kth smallest

- src/Statistics/Regression/Methods/LeastSquares.php
- tests/Statistics/Regression/LinearThroughPointTest.php
Reviewing against Excel, this will work for polynomial and multilinear through origin as well.
> Fixed Sum of squares for regression through point

- README.md
- src/NumericalAnalysis/NumericalIntegration/NumericalIntegration.php
- src/NumericalAnalysis/NumericalIntegration/SimpsonsRule.php
- src/NumericalAnalysis/NumericalIntegration/TrapezoidalRule.php
- tests/NumericalAnalysis/NumericalIntegration/SimpsonsRuleTest.php
- tests/NumericalAnalysis/NumericalIntegration/TrapezoidalRuleTest.php
Reflected changes in comments, child classes, tests, and readme examples.
> Made NumericalIntegration classes compatible with callback function inputs

- README.md
- src/NumericalAnalysis/NumericalIntegration/SimpsonsThreeEighthsRule.php
- src/NumericalAnalysis/RootFinding/BisectionMethod.php
- tests/NumericalAnalysis/RootFinding/BisectionMethodTest.php
Included a test and updated the readme
> Added the Bisection Method to RootFinding

- README.md
- src/NumericalAnalysis/RootFinding/BisectionMethod.php
- src/NumericalAnalysis/RootFinding/FixedPointIteration.php
- tests/NumericalAnalysis/RootFinding/FixedPointIterationTest.php
Included test and updated readme
> Added Fixed Point Iteration

- README.md
- src/NumericalAnalysis/RootFinding/SecantMethod.php
- tests/NumericalAnalysis/RootFinding/SecantMethodTest.php
Included test and updated readme
> Added Secant Method

- README.md
- src/NumericalAnalysis/RootFinding/BisectionMethod.php
- src/NumericalAnalysis/RootFinding/FixedPointIteration.php
- src/NumericalAnalysis/RootFinding/NewtonsMethod.php
- src/NumericalAnalysis/RootFinding/RootFindingValidation.php
- src/NumericalAnalysis/RootFinding/SecantMethod.php
- I put all common validation methods inside this new trait, and then removed duplicate code from individual classes
> Added RootFindingValidation trait and removed duplicate code

- README.md
- src/NumericalAnalysis/NumericalIntegration/MidpointRule.php
- src/NumericalAnalysis/NumericalIntegration/RectangleMethod.php
- tests/NumericalAnalysis/NumericalIntegration/MidpointRuleTest.php
- tests/NumericalAnalysis/NumericalIntegration/RectangleMethodTest.php
> Added Rectangle Method to Numerical Integration

- README.md
- src/NumericalAnalysis/NumericalIntegration/BoolesRule.php
- tests/NumericalAnalysis/NumericalIntegration/BoolesRuleTest.php
> Added Booles Rule

- src/NumericalAnalysis/NumericalIntegration/BoolesRule.php
- src/NumericalAnalysis/NumericalIntegration/SimpsonsRule.php
- src/NumericalAnalysis/NumericalIntegration/SimpsonsThreeEighthsRule.php
- src/NumericalAnalysis/NumericalIntegration/Validation.php
Allowed me to remove a lot of duplicate code
> Introduced Validation Trait to Numerical Integration techniques

- README.md
- src/NumericalAnalysis/Interpolation/Interpolation.php
- src/NumericalAnalysis/Interpolation/LagrangePolynomial.php
- tests/NumericalAnalysis/Interpolation/InterpolationTest.php
- tests/NumericalAnalysis/Interpolation/LagrangePolynomialTest.php
Included tests for both, and added Interpolation to README with Lagrange Polynomials as a feature
> Added Lagrange Polynomials with parent class Interpolation

- README.md
- src/Functions/Arithmetic.php
- src/NumericalAnalysis/Interpolation/Interpolation.php
- src/NumericalAnalysis/Interpolation/LagrangePolynomial.php
- tests/Functions/ArithmeticTest.php
- tests/NumericalAnalysis/Interpolation/InterpolationTest.php
- tests/NumericalAnalysis/Interpolation/LagrangePolynomialTest.php
Added capability to add and multiply functions (of one variable) to make new functions.
For example:
h(x) = f(x) + g(x)
and
h(x) = f(x) * g(x)
Note: these methods return functions themselves. This will allow for many more techniques to be constructed, such as Lagrange Interpolation, which depend on function addition and multiple to return functions themselves and not just evaluations of functions at a single point.
> Added function arithmetic

- README.md
- src/NumericalAnalysis/Interpolation/Interpolation.php
- src/NumericalAnalysis/Interpolation/NevillesMethod.php
- tests/NumericalAnalysis/Interpolation/LagrangePolynomialTest.php
- tests/NumericalAnalysis/Interpolation/NevillesMethodTest.php
Included test and updated readme
> Added Nevilles Method, slightly modified Interpolation parent class

- README.md
- src/NumericalAnalysis/Interpolation/NewtonPolynomialForward.php
- tests/NumericalAnalysis/Interpolation/NewtonPolynomialForwardTest.php
Included test and updated README
> Added Newton Polynomial (Forward)

- README.md
- src/NumericalAnalysis/NumericalDifferentiation/NumericalDifferentiation.php
- src/NumericalAnalysis/NumericalDifferentiation/ThreePointFormula.php
- tests/NumericalAnalysis/NumericalDifferentiation/NumericalDifferentiationTest.php
- tests/NumericalAnalysis/NumericalDifferentiation/ThreePointFormulaTest.php
Included tests for both classes and updated README
> Added Three Point Formula with parent class Numerical Differentiation

- README.md
- src/NumericalAnalysis/NumericalDifferentiation/FivePointFormula.php
- src/NumericalAnalysis/NumericalDifferentiation/ThreePointFormula.php
- tests/NumericalAnalysis/NumericalDifferentiation/FivePointFormulaTest.php
- tests/NumericalAnalysis/NumericalDifferentiation/ThreePointFormulaTest.php
Included test and update README
> Added Five Point Method

- src/Functions/Polynomial.php
- tests/Functions/PolynomialsTest.php
New, I'm planning on extending numerous techniques, such as:
- Polynomial integration
- Polynomial differentiation
- Polynomial arithmetic
> Added Polynomial class with automatic string conversion and evaluation methods

- README.md
- src/LinearAlgebra/Vector.php
- tests/LinearAlgebra/VectorTest.php
I noticed you didn't have a vector Cross Product method, so I created one.
> Created cross product method

- src/Functions/Polynomial.php
- tests/Functions/PolynomialTest.php
> Added polynomial addition and multiplication, fixed some bugs

- src/NumericalAnalysis/Interpolation/LagrangePolynomial.php
- tests/NumericalAnalysis/Interpolation/LagrangePolynomialTest.php
- tests/NumericalAnalysis/Interpolation/NevillesMethodTest.php
I was able to rewrite the Lagrange Polynomials with the polynomial class rather than constructing callback functions explicitly.
When running tests, I did run into roundoff error quite a few times. Thus, I added a slight modification to the tests that depend on the Lagrange Polynomials to account for this.
> Refactored Lagrange Polynomial to use polynomial class

- src/NumericalAnalysis/Interpolation/LagrangePolynomial.php
- src/NumericalAnalysis/NumericalIntegration/BoolesRule.php
- src/NumericalAnalysis/NumericalIntegration/RectangleMethod.php
- src/NumericalAnalysis/NumericalIntegration/SimpsonsRule.php
- src/NumericalAnalysis/NumericalIntegration/SimpsonsThreeEighthsRule.php
- src/NumericalAnalysis/NumericalIntegration/TrapezoidalRule.php
The formulas in these techniques are derived by simply interpolating the set of points for each iteration, and then integrating the interpolating polynomial.
Now that we have the tools of the Polynomial class, we can simply replace those formulas with two steps:
1. Interpolate the set of points
2. Find the definite integral of the interpolating polynomial
I also realized we can extend the Lagrange Polynomial to interpolate just one point, and not just sets with two points or more. The result of this "zeroth degree" Lagrange Polynomial is just that: a constant polynomial P(x) = C, where C is the y-component of our input point.
> Refactored Newton-Cotes techniques to use Lagrange Polynomials and Polynomial Integration

- src/Algebra.php
- src/ComplexNumbers/ComplexNumber.php
- tests/Algebra/AlgebraTest.php
- tests/ComplexNumbers/ComplexNumberTest.php
- tests/phpunit.xml
This patch adds a complex number class. This class is used in the quadratic function for cases where the roots of the polynomial are complex.
> Complex Number Class and Complex Root of Quadratic Function

- src/Probability/Distribution/Continuous/Continuous.php
> Refactor Continuous Inverse Method

- src/Number/Complex.php
- src/Number/MatrixObjectInterface.php
I will use this to ensure that any object used in a Object matrix has the necessary methods to work correctly.
> Add an Interface

- src/LinearAlgebra/MatrixFactory.php
- src/LinearAlgebra/ObjectSquareMatrix.php
- src/LinearAlgebra/ObjectSquarematrix.php
- tests/LinearAlgebra/ObjectSquareMatrixTest.php
With this class, matrix addition, subtraction, and determinants can be performed on objects.
> Created ObjectSquareMatrix

- src/LinearAlgebra/Eigenvalue.php
- tests/LinearAlgebra/EigenvalueTest.php
This is a much improved eigenvector method from what I had previously. Now, when the same eigenvalue is present multiple times, the two (or more) eigenvectors are orthogonal. There were cases where the previous algorithm wouldn't work, and this covers them.
> Refactored Eigenvalue and added Eigenvector method

- src/Probability/Distribution/Continuous/Gamma.php
- tests/Probability/Distribution/Continuous/GammaTest.php
> Add mean to gamma distribution

- src/Probability/Distribution/Continuous/Beta.php
- src/Probability/Distribution/Continuous/Continuous.php
- tests/Probability/Distribution/Continuous/BetaTest.php
Here is a first step. I added a generic parent-level constructor, and transitioned the Beta distribution to be non-static.
> Transitioning distributions to non-static

- src/Probability/Distribution/Continuous/Cauchy.php
- src/Probability/Distribution/Continuous/ChiSquared.php
- src/Probability/Distribution/Continuous/Continuous.php
- src/Probability/Distribution/Continuous/DiracDelta.php
- src/Probability/Distribution/Continuous/F.php
- src/Probability/Distribution/Continuous/LogLogistic.php
- src/Probability/Distribution/Continuous/Logistic.php
- src/Probability/Distribution/Continuous/NoncentralT.php
- src/Probability/Distribution/Continuous/Normal.php
- src/Probability/Distribution/Continuous/StandardNormal.php
- src/Probability/Distribution/Continuous/StudentT.php
- src/Probability/Distribution/Continuous/Weibull.php
- src/Statistics/ANOVA.php
- src/Statistics/Correlation.php
- src/Statistics/KernelDensityEstimation.php
- src/Statistics/Regression/Methods/LeastSquares.php
- src/Statistics/Significance.php
- tests/Probability/Distribution/Continuous/CauchyTest.php
- tests/Probability/Distribution/Continuous/ChiSquaredTest.php
- tests/Probability/Distribution/Continuous/DiracDeltaTest.php
- tests/Probability/Distribution/Continuous/FTest.php
- tests/Probability/Distribution/Continuous/LimitsTest.php
- tests/Probability/Distribution/Continuous/LogLogisticTest.php
- tests/Probability/Distribution/Continuous/LogisticTest.php
- tests/Probability/Distribution/Continuous/NormalTest.php
- tests/Probability/Distribution/Continuous/StandardNormalTest.php
- tests/Probability/Distribution/Continuous/StudentTTest.php
- tests/Probability/Distribution/Continuous/WeibullTest.php
> Distribution update (#23)

- src/Probability/Distribution/Continuous/Pareto.php
- tests/Probability/Distribution/Continuous/LimitsTest.php
- tests/Probability/Distribution/Continuous/ParetoTest.php
Continuous Distributions are complete.
> Update Pareto Distribution

- src/Probability/Distribution/Continuous/Continuous.php
- src/Probability/Distribution/Discrete/Binomial.php
- src/Probability/Distribution/Distribution.php
- tests/Probability/Distribution/Discrete/BernoulliTest.php
- tests/Probability/Distribution/Discrete/BinomialTest.php
- tests/Probability/Distribution/Discrete/LimitsTest.php
Moved the default constructor up one level, and refactored Binomial
> Beginning Discrete Distributions

- src/Probability/Distribution/Discrete/Binomial.php
- src/Probability/Distribution/Discrete/NegativeBinomial.php
- src/Probability/Distribution/Discrete/Pascal.php
- src/Probability/Distribution/Discrete/Poisson.php
- src/Probability/Distribution/Discrete/ShiftedGeometric.php
- src/Probability/Distribution/Discrete/Uniform.php
- tests/Probability/Distribution/Discrete/LimitsTest.php
- tests/Probability/Distribution/Discrete/NegativeBinomialTest.php
- tests/Probability/Distribution/Discrete/PascalTest.php
- tests/Probability/Distribution/Discrete/PoissonTest.php
- tests/Probability/Distribution/Discrete/ShiftedGeometricTest.php
- tests/Probability/Distribution/Discrete/UniformTest.php
https://github.com/markrogoyski/math-php/issues/247
* NegativeBinomial (and Pascal)
* Poisson
* ShiftedGeometric
* Uniform
> Discrete refactoring

- src/Probability/Distribution/Continuous/Beta.php
- src/Probability/Distribution/Continuous/Cauchy.php
- src/Probability/Distribution/Continuous/ChiSquared.php
- src/Probability/Distribution/Continuous/Continuous.php
- src/Probability/Distribution/Continuous/ContinuousInterface.php
- src/Probability/Distribution/Continuous/DiracDelta.php
- src/Probability/Distribution/Continuous/F.php
- src/Probability/Distribution/Continuous/Gamma.php
- src/Probability/Distribution/Continuous/Laplace.php
- src/Probability/Distribution/Continuous/LogLogistic.php
- src/Probability/Distribution/Continuous/LogNormal.php
- src/Probability/Distribution/Continuous/Logistic.php
- src/Probability/Distribution/Continuous/NoncentralT.php
- src/Probability/Distribution/Continuous/Normal.php
- src/Probability/Distribution/Continuous/Pareto.php
- src/Probability/Distribution/Continuous/StandardNormal.php
- src/Probability/Distribution/Continuous/StudentT.php
- src/Probability/Distribution/Continuous/Uniform.php
- src/Probability/Distribution/Continuous/Weibull.php
- tests/Probability/Distribution/Continuous/DiracDeltaTest.php
https://github.com/markrogoyski/math-php/issues/247
* Added a continuous interface
* unified cdf and pdf signatures to have float type
* removed some unnecessary docblock lines
Please verify that it makes sense to say that the dirac delta distribution has a mean of 0.
https://github.com/balping/math-php/blob/2bbb17dd8f19cd0f38641696efa479103f16a8b5/src/Probability/Distribution/Continuous/DiracDelta.php#L98
> Distributions: continuous interface

- README.md
- src/LinearAlgebra/Matrix.php
- tests/LinearAlgebra/MatrixOperationsTest.php
Create an arbitrary sized submatrix
> Submatrix Function

- src/Statistics/Regression/TheilSen.php
If two points in the data-set have the same x values, there will be a divide by zero.
> Fix Divide by zero

- src/Sequence/NonInteger.php
- tests/Sequence/NonIntegerTest.php
Created sequences of harmonic numbers and the hyperharmonic numbers
> Harmonic numbers

- README.md
small typing mistake. It was ":" instead of ";"
> just a ; on the end

- src/LinearAlgebra/Matrix.php
- tests/LinearAlgebra/MatrixDataProvider.php
- tests/LinearAlgebra/MatrixPropertiesTest.php
If a matrix is normal, it is diagonalizable, and has eigenvalues and eigenvectors
> IsNormal matrix

- src/Functions/Special.php
> Simplified code with spaceship operator

- src/Arithmetic.php
- tests/Arithmetic/ArithmeticTest.php
- tests/phpunit.xml
Extending cubeRoot to any integer, was part of the JK pull request.
> Integer root

- composer.json
- src/Exception/FunctionFailedToConvergeException.php
- src/LinearAlgebra/Eigenvalue.php
- src/LinearAlgebra/MatrixFactory.php
- tests/LinearAlgebra/EigenvalueTest.php
- tests/LinearAlgebra/MatrixFactoryTest.php
This is another algorithm that easily calculates both eigenvalues and eigenvectors, so It might be worthwhile considering how to combine the two static classes into one.
> Power iteration Eigenvalue calculation

- src/LinearAlgebra/Matrix.php
- tests/LinearAlgebra/MatrixDataProvider.php
- tests/LinearAlgebra/MatrixPropertiesTest.php
> Matrix isIdempotent property

- src/LinearAlgebra/Decomposition/LU.php
- src/LinearAlgebra/Decomposition/QR.php
- src/LinearAlgebra/Decompositions/LU.php
- src/LinearAlgebra/Matrix.php
This change is internal-only; it does not affect the user.
> Moved LU Decomposition to separate class and new namespace

- src/LinearAlgebra/Matrix.php
- tests/LinearAlgebra/MatrixDataProvider.php
- tests/LinearAlgebra/MatrixPropertiesTest.php
Taken from the SVD pull request. Let's merge in some of the smaller independent pieces and I'll start working on that again.
> isRectangularDiagonal Function

- src/LinearAlgebra/Decomposition/Cholesky.php
- src/LinearAlgebra/Decomposition/Crout.php
- src/LinearAlgebra/Decomposition/Decomposition.php
- src/LinearAlgebra/Decomposition/DecompositionBase.php
- src/LinearAlgebra/Decomposition/LU.php
- src/LinearAlgebra/Decomposition/QR.php
Collecting some of the common functions together in one place. Reducing lines of code, increasing coverage.
> DecompositionBase

- src/LinearAlgebra/Matrix.php
- tests/LinearAlgebra/MatrixPropertiesTest.php
Since real numbers are a subset of the complex numbers, complex properties would be appropriate.
* Added conjugateTranspose()
* Added isUnitary()
* Added isHermitian()
> Complex Properties

- src/NumberTheory/Integer.php
Not the best algo, but an improvement
prime factor 2..1e5:
before: 15.95s
after: 0.09s
> optimize prime factorizations

- src/SetTheory/Set.php
- tests/SetTheory/SetOperationsTest.php
https://github.com/markrogoyski/math-php/pull/362 Merged into develop instead of master.
> Set-Theory: n-ary Cartesian product

- README.md
- src/LinearAlgebra/Vector.php
- tests/LinearAlgebra/VectorAngleTest.php
- tests/LinearAlgebra/VectorDistanceTest.php
Hey @markrogoyski,
here are my suggested changes regarding #377.
Since this is my first "real" contribution to an Open Source project, please be nice to me :-D
-Florian
> Add: Angle and distances between two vectors

- src/NumericalAnalysis/Interpolation/RegularGridInterpolator.php
- tests/NumericalAnalysis/Interpolation/RegularGridInterpolatorTest.php
Implementation multidimensional interpolation on regular grids. 
Closes #382
> Implementation multidimensional interpolation on regular grids.

- tests/Probability/Distribution/Multivariate/NormalTest.php
Instead of creating Matrix directly.
> Use the MatrixFactory in test
